#import "../lib.typ": *
#import "../utils.typ": *
#import "@preview/splash:0.3.0": tailwind
#import "@preview/big-todo:0.2.0": *

#pagebreak()

= Contributions

#col[
  == Markus Heming
  === Project Phase

  I was involved in the initial project planning phase, contributing to the conceptualization and methodology design. During the project implementation phase, I was substantially involved in all real-world RT60 measurements, which formed the core foundation of our dataset. This involved systematic gathering of room impulse responses and room images across diverse TH Köln office environments.
  I also participated in the synthetic room data generation process alongside other team members, contributing to the creation of additional training data for our neural network model by creating 10 rooms with 105 room pictures each. Initially, I developed one room asset to support this synthetic data pipeline, though this asset was ultimately not utilized.

  Regarding model training, I was not highly involved in this phase of the project. I conducted one training session, which proved redundant and did not yield meaningful results compared to other team members.

  I was absent from the project for three weeks during late June and early July due to participation in a Summer School program in Kyoto, Japan.

  === Documentation Phase

  My documentation contributions encompassed several sections of the technical report and presentation materials. I actively worked on the related works section, conducting literature review and providing comprehensive coverage of existing research in acoustic parameter estimation and computer vision applications in room acoustics. I contributed significantly to the discussion section, offering critical analysis of our experimental results, identifying system limitations, and proposing directions for future research improvements.

  Additionally, I participated in writing the conclusion section, synthesizing our findings and their implications for RT60 estimation using single-image neural network approaches. Throughout the documentation process, I provided comprehensive feedback on different sections, contributing to the overall coherence and quality of the technical report. I was also actively involved in developing the project poster for the poster session.

  == David Klein
  === Project Phase

  During the project phase, I contributed to both data collection and model development. I participated in real-world data collection, taking a total of 63 images of rooms over multiple days. Additionally I generated three rooms using Blender, adding to the existing synthetic data generated by the other team members.

  We decided early on that we wanted to try experimenting with models, already trained on the Places2 dataset. Because of that I conducted research into various models pretrained on the Places2 dataset, ultimately implementing both ResNet18 and ResNet50 architectures. The ResNet50 backbone was subsequently adopted by Leo and used for our initial baseline model. I also conducted two more experiments using a custom backbone and reusing the v1.10 architecture to test our data seperately, as listed in @exp_result_summary.

  In an attempt to bridge the domain gap between our real and synthetic data I set up an image-to-image translation model. After around 31 hours of training the results were underwhelming. While there was a noticeable improvement in the appearance of indirect lighting and reflections (e.g. light reflections on tables had an orange hue from the blinds), the structure of the rooms was also highly distorted in some cases. I ultimately decided not to invest more time into adapting our dataset using this method.

  // spent 2 days collecting real-world data
  // generated 3 rooms using blender
  // researched different models for places2 dataset
  // ended up implementing resnet18 and resnet50, which was used by leo for the first baseline
  // built a model with a custom u-net inspired backbone
  // conducted an experiment using v1.10 architecture to analyze domain gap
  // tried using image to image translation to bridge domain gap
  //  -> trained model, but scrapped

  === Documentation Phase

  During the documentation phase I contributed to the dataset section, giving more insight on how we analyzed the recordings and adding some statistics about the amount of data gathered. I also wrote the sections about my own experiments, describing my methodology and results in the context of the project.


  == Jonathan Kron
  === Project Phase
  // - created the room generator in Blender
  //   - modelling of chair, tables and other assets explained in @synth_data_gen
  //   - wrote scripts to export room data (for use in Treble)
  //   - wrote script to make adjusting the room generator easier
  // - 10 Räume generiert
  // - 7 official model experiments as listed in @exp_result_summary
  //   - some smaller experiments regarding resolution that didn't go anywhere
  // - collaborated with Leo on the "simple experiment"
  //   - adjusted the room generator
  //   - generated the entire new dataset
  //   - together with leo adjusted model, train and evaluate scripts, as well as wrote the simulation script for the new roomtypes as explained in @simple_experiment
  //
  During the project phase, I was primarily responsible for the creation and implementation of the synthetic room generator in Blender. This included the detailed modeling of various assets such as chairs, tables, and wall assets, as documented in @synth_data_gen. To enable further processing, I developed scripts that export the generated room data in formats compatible with Leo Kling's Treble script. Additionally, I authored a script that facilitates quick adjustments to the room generator's parameters and configuration, streamlining dataset creation.

  In preparation for potential issues with Treble, I also dedicated time to learning the I-SIMPA simulation tool. This included an attempt to export the generated room geometries to a format usable by I-SIMPA, in order to evaluate it as a fallback solution for acoustic simulation. Although this alternative path was not ultimately pursued further, the exploration helped reduce the risk of pipeline failure due to software limitations or incompatibilities.

  In total, I generated 10 distinct room configurations. I conducted seven official experiments with neural network models as listed in the @exp_result_summary. In parallel, I also explored minor experiments involving image resolution; however, these did not lead to conclusive results.

  I collaborated closely with Leo on the "simple experiment" subproject. My contributions included adapting the room generator for the newly defined room types and generating the corresponding dataset in its entirety. Together with Leo, I modified the model architecture and updated the training and evaluation scripts accordingly. We also co-developed a new simulation script tailored to the specific requirements of the simplified room configurations, as detailed in the @simple_experiment documentation.

  === Documentation Phase

  // - wrote major parts of the documentation including:
  //   - collaborated with Milan on the abstract
  //   - wrote Introduction and motivation
  //   - collaborated with Milan on fundamental-concepts regarding reverberation time
  //   - co-authored dataset, contributing to the synthetic generation explaination
  //   - co-authored the simple experiment
  //   - contributed to the experiemnts section
  //   - wrote t-sne section
  //   - created the gantt charts

  In the documentation phase, I was responsible for substantial portions of the final report. I collaborated with Milan on the abstract and co-authored the section on fundamental concepts of reverberation time. I also wrote the Introduction and Motivation section based on the first drafts by Milan Jezovsek.

  Regarding the dataset, I co-authored the corresponding documentation, focusing on the synthetic data generation process. I also co-authored the section describing the simple experiment and contributed to the broader discussion in the experiments section. Additionally, I was responsible for writing the subsection on the t-SNE visualizations used to evaluate feature-space clustering. Finally, I designed and created the Gantt charts used to visualize our project timeline.

  == Milan Jezovsek
  === Project Phase
  During the project development phase, I contributed to multiple aspects of the research pipeline, ranging from data collection to architectural experimentation. I participated in real-world data collection efforts to build the empirical dataset and leveraged Jonathan's tooling to generate synthetic training data, expanding the available data resources for model development. My primary focus centered on architectural experimentation, particularly through the implementation of experiments v1.14 and v1.15, which investigated the integration of spatial attention mechanisms into the existing model framework. These experiments aimed to enhance the model's ability to focus on acoustically relevant spatial features within room imagery for improved RT60 prediction accuracy.

  === Documentation Phase
  In the documentation phase, I made substantial contributions to the project's technical documentation by initializing the fundamental concepts section and comprehensively developing the reverberation time components. This foundational work established the theoretical groundwork for the reverberation time section, which was subsequently restructured and expanded through collaborative efforts with other team members and myself. Additionally, I enriched the experiments and results documentation by incorporating detailed analyses of experiments v1.14 and v1.15, providing comprehensive coverage of the spatial attention investigation including methodology, performance metrics, and critical evaluation of the approach's effectiveness for visual-acoustic RT60 estimation. I also wrote the first drafts for our abstract as well as the Introduction and Motivation sections, which were later refined through collaborative efforts by Jonathan Kron.

  == Philipp Wendt
  === Project Phase

  During the project implementation phase, my contributions included the comprehensive collection and curation of real-world acoustic and image data, establishing a foundation for the reverberation time estimation system. This involved systematic gathering of room impulse responses and corresponding RT60 measurements across diverse office rooms. Following data collection, I conducted data analysis to ensure the data was not faulty.

  The model training phase constituted a significant portion of my technical contributions, where I implemented and optimized convolutional neural network architectures. This involved systematic experimentation with various CNN configurations, including transfer learning approaches utilizing pre-trained models such as Places365-trained ResNet architectures. Additionally, I conducted comprehensive model analysis to evaluate performance and robustness, including systematic assessment of prediction accuracy across different captured environments.

  === Documentation Phase

  My documentation contributions included both theoretical exposition and analysis presentation. I provided comprehensive explanations of neural network fundamentals and deep learning principles. I contributed significantly to the structural organization of the technical report and, in collaboration with Leo, co-authored the dataset section documenting data collection procedures and preprocessing methodologies.

  Additionally, I focused on comprehensive explanation of experimental procedures and results. I contributed to expanding the related works section through literature review of relevant research in acoustic parameter estimation and machine learning applications in room acoustics. Finally, I made contributions to the discussion section, providing critical analysis of results, identification of limitations, and suggestions for future research directions.



  == Leo Kling
  === Project Phase

  During the project phase, I developed comprehensive scripts for recording and analyzing room impulse responses (RIR). These scripts facilitated both the collection of acoustic data and subsequent analysis of the recordings. I conducted extensive data exploration and cleanup of the real-world data to ensure quality and consistency, and personally participated in one day of real data recording sessions.

  I was solely responsible for all synthetic impulse response generation using the Treble framework. This involved creating the Treble script, generating the synthetic RIRs, researching and implementing alternatives to Treble for synthetic data generation, and conducting thorough synthetic data exploration, cleanup, and analysis. Using Jonathan's room generator, I generated 10 synthetic rooms with varying acoustic properties.

  To facilitate collaboration, I implemented a dataset synchronization solution using WebDAV and Sciebo, ensuring all team members had access to the latest data. I also developed the dataset splitting script to properly separate training, validation, and testing data. I created the initial baseline model for our experiments and conducted a total of 10 experiments as documented in @exp_result_summary.

  I collaborated closely with Jonathan on the "simple experiment", where we jointly developed the model architecture and training methodology, created a new simulation script for room impulse responses, and performed detailed analysis of the experimental results.

  === Documentation Phase

  In the documentation phase, I authored the dataset section, detailing both real-world and synthetic data collection and processing. I wrote the experimental methodology section, explaining our approach to model training and evaluation. I collaborated with other team members on documenting the experiments and results, as well as on the related works section.

  For the fundamental concepts chapter, I contributed sections on theoretical calculation methods, Reverberation Time (RT60), and simulation methods. Finally, I co-authored the conclusion and discussion sections together with Markus, synthesizing our findings and identifying future research directions.

]
